"""Quadlet generation: eval execution as systemd user container units.

A container run is expressed as a ``.container`` unit under
``~/.config/containers/systemd/user/`` (Quadlet, podman's systemd
integration), started with ``systemctl --user start --wait`` so the exit
code is the container's. GPU devices pass through with ``Device=`` paths
(or a CDI qualifier such as ``nvidia.com/gpu=all`` where the host
registers one). Images should be digest-pinned for reproducible runs; an
optional ``.build`` unit pairs with a locked Containerfile when the image
is assembled locally.
"""

from __future__ import annotations

import dataclasses
import pathlib
import re
import subprocess

_UNIT_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


@dataclasses.dataclass(frozen=True)
class ContainerSpec:
    """One eval container: image, command, mounts, devices, environment."""

    name: str
    image: str
    exec_cmd: tuple[str, ...]
    workdir: str = "/work"
    # (host path, container target, read-only) triples
    volumes: tuple[tuple[str, str, bool], ...] = ()
    # Device paths (or CDI qualifiers) to pass through, e.g. /dev/nvidia0
    gpu_devices: tuple[str, ...] = ()
    env: tuple[tuple[str, str], ...] = ()

    def __post_init__(self) -> None:
        if not _UNIT_NAME_RE.match(self.name):
            raise ValueError(f"container name {self.name!r} must match {_UNIT_NAME_RE.pattern}")
        if not self.exec_cmd:
            raise ValueError("exec_cmd must not be empty")


def unit_name(spec: ContainerSpec) -> str:
    return f"weco-{spec.name}.service"


def render_container_unit(spec: ContainerSpec) -> str:
    lines = [
        f"# Generated by weco local (Quadlet). Source spec: {spec.name}",
        "[Unit]",
        f"Description=weco eval container {spec.name}",
        "",
        "[Container]",
        f"Image={spec.image}",
    ]
    lines.append("Exec=" + " ".join(spec.exec_cmd))
    lines.append(f"WorkingDirectory={spec.workdir}")
    for host, target, read_only in spec.volumes:
        options = ",ro" if read_only else ""
        lines.append(f"Volume={host}:{target}{options}")
    for device in spec.gpu_devices:
        lines.append(f"Device={device}")
    for key, value in spec.env:
        lines.append(f'Environment="{key}={value}"')
    lines += [
        "",
        "[Service]",
        "# A oneshot-style eval run: systemctl start --wait blocks for the exit.",
        "RemainAfterExit=no",
        "",
        "[Install]",
        "WantedBy=default.target",
        "",
    ]
    return "\n".join(lines)


def unit_path(spec: ContainerSpec, base: pathlib.Path | None = None) -> pathlib.Path:
    root = base if base is not None else pathlib.Path.home() / ".config" / "containers" / "systemd" / "user"
    return pathlib.Path(root) / f"weco-{spec.name}.container"


def install_unit(spec: ContainerSpec, base: pathlib.Path | None = None) -> pathlib.Path:
    path = unit_path(spec, base)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_container_unit(spec), encoding="utf-8")
    return path


def run_unit(
    spec: ContainerSpec,
    *,
    base: pathlib.Path | None = None,
    runner=subprocess.run,
    tail: str = "200",
) -> int:
    """Install the unit, reload the user manager, and run it to completion.

    ``runner`` is injectable for tests; in production each call is a real
    ``systemctl --user`` invocation. On failure the recent journal lines for
    the unit are printed to stderr so the eval's error is visible.
    """
    import sys

    path = install_unit(spec, base)
    reload_result = runner(["systemctl", "--user", "daemon-reload"], check=False)
    if reload_result.returncode != 0:
        print(f"weco local: systemctl --user daemon-reload failed (rc {reload_result.returncode})", file=sys.stderr)
        return reload_result.returncode
    start_result = runner(["systemctl", "--user", "start", "--wait", unit_name(spec)], check=False)
    if start_result.returncode != 0:
        journal = runner(["journalctl", "--user", "-u", unit_name(spec), "-n", tail], check=False, capture_output=True, text=True)
        print(journal.stdout or "", file=sys.stderr)
    return start_result.returncode
