"""Tests for the local execution drivers and the local loop (no network)."""

from __future__ import annotations

import hashlib
import io
import json
import pathlib
import tarfile
from types import SimpleNamespace

import pytest

from weco.local.chroot import ChrootError, ChrootManifest, build_rootfs, systemd_run_argv, unpack_rootfs, verify_sha256
from weco.local.loop import local_optimize, make_opencode_step, parse_metric
from weco.local.quadlet import ContainerSpec, install_unit, render_container_unit, run_unit, unit_name


# ── Quadlet ───────────────────────────────────────────────────────────


def spec() -> ContainerSpec:
    return ContainerSpec(
        name="eval-speed",
        image="registry.example/weco-eval@sha256:abc",
        exec_cmd=("bash", "/work/.weco/evaluate.sh"),
        volumes=(("/home/me/proj", "/work", False), ("/home/me/proj/data", "/data", True)),
        gpu_devices=("/dev/nvidia0",),
        env=(("WECO_TASK", "speed"),),
    )


def test_container_unit_golden():
    text = render_container_unit(spec())
    assert text == (
        "# Generated by weco local (Quadlet). Source spec: eval-speed\n"
        "[Unit]\n"
        "Description=weco eval container eval-speed\n"
        "\n"
        "[Container]\n"
        "Image=registry.example/weco-eval@sha256:abc\n"
        "Exec=bash /work/.weco/evaluate.sh\n"
        "WorkingDirectory=/work\n"
        "Volume=/home/me/proj:/work\n"
        "Volume=/home/me/proj/data:/data,ro\n"
        "Device=/dev/nvidia0\n"
        'Environment="WECO_TASK=speed"\n'
        "\n"
        "[Service]\n"
        "# A oneshot-style eval run: systemctl start --wait blocks for the exit.\n"
        "RemainAfterExit=no\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def test_container_spec_validates_name_and_command():
    with pytest.raises(ValueError):
        ContainerSpec(name="Bad Name", image="x", exec_cmd=("true",))
    with pytest.raises(ValueError):
        ContainerSpec(name="ok", image="x", exec_cmd=())


def test_install_unit_writes_under_user_quadlet_dir(tmp_path):
    path = install_unit(spec(), base=tmp_path)
    assert path == tmp_path / "weco-eval-speed.container"
    assert "[Container]" in path.read_text(encoding="utf-8")


def test_run_unit_reloads_starts_waits_and_tails_journal_on_failure(tmp_path):
    calls: list[list[str]] = []

    def fake_runner(argv, **kwargs):  # noqa: ANN003
        calls.append(list(argv))
        rc = 1 if "start" in argv else 0
        stdout = "eval crashed" if "journalctl" in argv else ""
        return SimpleNamespace(returncode=rc, stdout=stdout, stderr="")

    rc = run_unit(spec(), base=tmp_path, runner=fake_runner)
    assert rc == 1
    assert calls[0] == ["systemctl", "--user", "daemon-reload"]
    assert calls[1] == ["systemctl", "--user", "start", "--wait", unit_name(spec())]
    assert calls[2][:3] == ["journalctl", "--user", "-u"]


# ── Chroot ────────────────────────────────────────────────────────────


def manifest() -> ChrootManifest:
    return ChrootManifest(
        name="gpu-eval",
        rootfs_url="https://example/rootfs.tar.gz",
        rootfs_sha256="0" * 64,
        command=("/bin/sh", "-c", "bash /work/.weco/evaluate.sh"),
        device_binds=("/dev/nvidia0", "/dev/nvidiactl"),
    )


def make_archive(tmp_path: pathlib.Path, payload: dict[str, str]) -> pathlib.Path:
    archive = tmp_path / "rootfs.tar.gz"
    with tarfile.open(archive, "w:gz") as tar:
        for name, content in payload.items():
            data = content.encode()
            info = tarfile.TarInfo(name=name)
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))
    return archive


def test_manifest_roundtrip_and_validation():
    data = {
        "name": "gpu-eval",
        "rootfs_url": "https://example/rootfs.tar.gz",
        "rootfs_sha256": "0" * 64,
        "command": ["/bin/sh", "-c", "true"],
        "device_binds": ["/dev/nvidia0"],
    }
    parsed = ChrootManifest.from_dict(data)
    assert parsed.command == ("/bin/sh", "-c", "true")
    assert parsed.device_binds == ("/dev/nvidia0",)
    with pytest.raises(ChrootError):
        ChrootManifest.from_dict({"name": "x"})
    with pytest.raises(ChrootError):
        ChrootManifest.from_dict({**data, "command": "not-a-list"})


def test_verify_sha256_rejects_mismatch(tmp_path):
    archive = make_archive(tmp_path, {"etc/motd": "hi\n"})
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    verify_sha256(archive, digest)
    with pytest.raises(ChrootError):
        verify_sha256(archive, "0" * 64)


def test_unpack_rejects_traversal_members(tmp_path):
    archive = tmp_path / "evil.tar"
    with tarfile.open(archive, "w") as tar:
        data = b"boom"
        info = tarfile.TarInfo(name="../escape")
        info.size = len(data)
        tar.addfile(info, io.BytesIO(data))
    with pytest.raises(ChrootError):
        unpack_rootfs(archive, tmp_path / "out")


def test_build_rootfs_is_reproducible(tmp_path):
    archive = make_archive(tmp_path, {"etc/motd": "hello\n", "bin/probe": "#!/bin/sh\n"})
    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    m = ChrootManifest(name="repro", rootfs_url="https://example/rootfs.tar.gz", rootfs_sha256=digest, command=("/bin/probe",))
    first = build_rootfs(m, archive=archive, root=tmp_path / "a")
    second = build_rootfs(m, archive=archive, root=tmp_path / "b")
    listing = lambda root: sorted(str(p.relative_to(root)) for p in root.rglob("*"))  # noqa: E731
    assert listing(first) == listing(second)
    lock_a = (tmp_path / "a" / "repro" / "manifest.lock").read_text(encoding="utf-8")
    lock_b = (tmp_path / "b" / "repro" / "manifest.lock").read_text(encoding="utf-8")
    assert lock_a == lock_b
    assert json.loads(lock_a)["rootfs_sha256"] == digest


def test_systemd_run_argv_golden(tmp_path):
    m = manifest()
    rootfs = tmp_path / "rootfs"
    workspace = tmp_path / "proj"
    argv = systemd_run_argv(m, rootfs, workspace=workspace)
    assert argv == [
        "systemd-run",
        "--user",
        "--collect",
        "--wait",
        "--unit=weco-chroot-gpu-eval",
        f"--property=RootDirectory={rootfs}",
        "--property=WorkingDirectory=/work",
        f"--property=BindPaths={workspace}:/work",
        "--property=BindPaths=/dev/nvidia0:/dev/nvidia0",
        "--property=BindPaths=/dev/nvidiactl:/dev/nvidiactl",
        "/bin/sh",
        "-c",
        "bash /work/.weco/evaluate.sh",
    ]


# ── The local loop ────────────────────────────────────────────────────


def test_parse_metric_takes_last_matching_line():
    output = "junk\nspeedup: 1.2\nnoise\nspeedup: 1.5\nother: 9"
    assert parse_metric(output, "speedup") == 1.5
    assert parse_metric(output, "missing") is None
    assert parse_metric("speedup: not-a-number", "speedup") is None


def test_local_optimize_end_to_end_with_fake_harness(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "value.txt").write_text("100\n", encoding="utf-8")

    calls: list[tuple[int, float | None]] = []

    def fake_harness(step: int, best: float | None) -> None:
        calls.append((step, best))
        # Each step improves the "latency" by ten.
        (tmp_path / "value.txt").write_text(f"{100 - 10 * (step + 1)}\n", encoding="utf-8")

    summary = local_optimize(
        harness_step=fake_harness,
        eval_command='echo "latency_ms: $(cat value.txt)"',
        metric="latency_ms",
        maximize=False,
        steps=3,
        workdir=tmp_path,
    )

    assert [step for step, _ in calls] == [0, 1, 2]
    assert calls[0][1] is None  # the first step sees no best yet
    assert calls[1][1] == 90.0
    assert summary["best"] == {"step": 2, "value": 70.0}
    report = json.loads((tmp_path / ".weco" / "local-loop" / "report.json").read_text(encoding="utf-8"))
    assert report["best"]["value"] == 70.0
    steps_log = (tmp_path / ".weco" / "local-loop" / "steps.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(steps_log) == 3


def test_opencode_step_raises_when_harness_fails(tmp_path, monkeypatch):
    step = make_opencode_step(tmp_path, metric="m", maximize=True)

    def fake_bridge(*, prompt, agent, forwarded_args, console, stdout=None):  # noqa: ANN003
        return 3

    monkeypatch.setattr("weco.commands.start.opencode_bridge.run_opencode_bridge", fake_bridge)
    with pytest.raises(RuntimeError):
        step(0, None)
